name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libssh
      run: sudo apt-get update && sudo apt-get install libssh-dev

    - name: autoreconf
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: dist-check
      run: make dist
